### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Shazgul** [xvertile/Kraken#1]
Got the following Error while launching Kraken 😅

```

   __ __         __
  / //_/______ _/ /_____ ___
 / ,< / __/ _ '/  '_/ -_) _ \
/_/|_/_/  \_,_/_/\_\\__/_//_/

Advanced Proxy Checker
Loading proxies
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x28 pc=0x26040c]

goroutine 1 [running]:
github.com/enriquebris/goconcurrentqueue.(*FIFO).GetLen(0xc000018300?)
        C:/Users/daan/go/pkg/mod/github.com/enriquebris/goconcurrentqueue@v0.7.0/fifo_queue.go:225 +0x2c
main.StartChecker()
        C:/Users/daan/GolandProjects/Kraken/main.go:29 +0x90
main.main()
        C:/Users/daan/GolandProjects/Kraken/main.go:64 +0xf
```

**Comment by xvertile** [comment]
Set debug to true in the config.json.

this means that it cannot find your proxy file path. Please modify the
proxy-filepath in the config file and it will work just fine.
